### ISSUE TITLE
hm needs sticky bit set

### ISSUE THREAD

**Issue by SkewedZeppelin** [rusty-snake/fedora-extras#2]
https://github.com/rusty-snake/fedora-extras/blob/43e7af652c9164e3687af65813cd573a1be10b3a/hardened_malloc/hardened_malloc.spec#L37

Please see https://gist.github.com/SkewedZeppelin/7f293d64c1c651bdc21526519d9e192b

**Comment by rusty-snake** [comment]
Reopen to analyse "Sets 755 instead of 644".

**Comment by rusty-snake** [comment]
@SkewedZeppelin may I ask why 755 is "better" than 644? Because almost everything in my `/usr/lib64` (Fedora 39) has 755.

**Comment by SkewedZeppelin** [comment]
only because it is probably a bad idea to have 4755, since that'd be an executable suid, 4644 works and should be safer

but yes most libraries I saw are 0755 strangely, not too sure the reasoning there

**Comment by rusty-snake** [comment]
Seems to be historic reasons. For Linux 644 should be fine.

---

https://github.com/rusty-snake/fedora-extras/commit/454427529af922ea2837bcfb163e80c6ee3c16c3
